### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by teriyakifilet** [teriyakifilet/protospace-33801#1]
# URL
https://protospace-33801.herokuapp.com/

**Comment by kouhei-masuda** [comment]
@teriyakifilet さん、ご提出いただきありがとうございます！
ご返信が遅くなり大変申し訳ございませんでした。
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by kouhei-masuda** [comment]
<img width="1201" alt="スクリーンショット 2021-02-21 14 27 44" src="https://user-images.githubusercontent.com/53155744/108616561-adae8200-7451-11eb-8e86-9cd66912b24f.png">

**Comment by teriyakifilet** [comment]
@kouhei-masuda ご確認いただきありがとうございました！
